### ISSUE TITLE
Is `isProfile` supposed to include gist profiles?

### ISSUE THREAD

**Issue by yakov116** [refined-github/github-url-detection#117]
https://github.com/refined-github/github-url-detection/blob/f92d8887c2fbd9eb689eb7ac17b220344fc862dc/index.ts#L520-L523

I am getting an error in RGH
`profile-gists-link` and `show-user-top-repositories` due to `isProfile` working on gists.
https://gist.github.com/yakov116

**Comment by fregante** [comment]
I don’t think it should be. While the UI is similar, if I specify "isProfile" I wouldn't think of looking at gist. In my mind it's an entirely different site. I'd rather exclude it from `isProfile`
