### ISSUE TITLE
Create a logger option

### ISSUE THREAD

**Issue by yakov116** [refined-github/github-url-detection#124]
Not sure if this belongs here but it can useful in RH. Allow the user to pass a url and it returs all matches. Would be super nice if even the dom ones are returned.

**Comment by fregante** [comment]
You mean this? https://refined-github.github.io/github-url-detection/

No DOM detections though

**Comment by yakov116** [comment]
Yes

**Comment by fregante** [comment]
Outside the module this is as easy as:

``` js
import * as p from 'this'

Object.entries(p).forEach(([name, fn]) => fn() && console.log(name))
``` 

To allow this from within the module we’d need to move everything to a separate file and it might throw off some tree-shakers because we’re using every export. Not sure it’s worth it
