### ISSUE TITLE
Calls for major release

### ISSUE THREAD

**Issue by fregante** [refined-github/github-url-detection#133]
I'm going to release a breaking version. Anything else you'd like to see?

- https://github.com/refined-github/github-url-detection/pull/132
- https://github.com/refined-github/github-url-detection/pull/131
- https://github.com/refined-github/github-url-detection/pull/130
- #139 
- #138 
- #136

**Comment by kidonng** [comment]
Good timing! Just recently I want to add "organization level discussions" (example: https://github.com/orgs/github-community/discussions), this is how GitHub calls it:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/44045911/180604630-3a0fce86-a0ac-41aa-9815-6ef92f7be7f7.png">

But we already have a `isOrganizationDiscussion`, which would be better named `isTeamDiscussion`?

**Comment by yakov116** [comment]
Drop depreciated 
Maybe visit the conversation issue?

**Comment by fregante** [comment]
Are you talking about “conversations === issues and PRs”? We can’t change here, it’s a user-facing issue 

Or isConversation vs isConversationList?

**Comment by yakov116** [comment]
Is conversation list

**Comment by fregante** [comment]
Time to switch to `isIssueOrPRList`, etc

**Comment by fregante** [comment]
@kidonng mind sending a PR?

**Comment by fregante** [comment]
That's a lot of breaking changed 😃
